### ISSUE TITLE
[META]: Add clarity for common docs questions 

### ISSUE THREAD

**Issue by joan-ing** [xataio/mdx-docs#141]
### Priority

Low

### Description

There are some queries that come through the chat bot, that might need further clarification in our docs. The questions asked as of Sept 2023 can be found in this [spreadsheet](https://docs.google.com/spreadsheets/d/1XQualx8sRc7OTyDqd3dxhbrzK1EJwRIZKYCeVs36wYM/edit#gid=0).

### How will this impact users?

* A more intuitive and user-friendly documentation structure can facilitate quicker and more effective understanding, allowing users to find the information they need without unnecessary hassle.

* With clearer documentation, users might be able to solve more issues independently, possibly leading to a decrease in queries on Discord or Zendesk.

### Context

We have a chatbot that users can use to ask our docs questions. We have room for improving docs based on the [most frequently asked questions](https://docs.google.com/spreadsheets/d/1XQualx8sRc7OTyDqd3dxhbrzK1EJwRIZKYCeVs36wYM/edit#gid=0) in our docs 

![image](https://github.com/xataio/mdx-docs/assets/82058372/5aa03cd6-6cf2-429c-8b95-69aaa54dc400)

### Suggested resolution

We need to clean this data to:
- [x] Clean data in [spreadsheet](https://docs.google.com/spreadsheets/d/1XQualx8sRc7OTyDqd3dxhbrzK1EJwRIZKYCeVs36wYM/edit#gid=0)
- [x] Identify which questions should be clarified in docs 
- [ ] Add info to docs
